---
- name: Upgrade packages
  apt: upgrade=dist
  
- name: Install packages
  apt:
    name: ['fail2ban', 'git-core', 'letsencrypt', 'unzip', 'python-pip', 'python-dev']
    state: latest
    update_cache: yes
